format_version: v1.0
type: UniqueComponent
attributes: {id: drvMiim}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_MIIM_ETH_MODULE_ID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvMiim, value: _ETH_BASE_ADDRESS}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: drvMiim}
