format_version: v1.0
type: UniqueComponent
attributes: {id: drvPic32mEthmac}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_INTMAC_PHY_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPic32mEthmac, value: LAN8740}
- type: ElementPosition
  attributes: {x: '540', y: '20', id: drvPic32mEthmac}
