format_version: v1.0
type: UniqueComponent
attributes: {id: drvExtPhyLan8740}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_ETHPHY_MAC_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvExtPhyLan8740, value: ETHMAC}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: libdrvExtPhyLan8740}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drvPic32mEthmac}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: ETHMAC_PHY_Dependency}
- type: ElementPosition
  attributes: {x: '396', y: '16', id: drvExtPhyLan8740}
