format_version: v1.0
type: UniqueComponent
attributes: {id: net_Pres}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: NET_PRES_RTOS_DELAY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: NET_PRES_RTOS_STACK_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '8192'}
- type: ElementPosition
  attributes: {x: '20', y: '20', id: net_Pres}
