format_version: v1.0
type: GroupComponent
attributes: {displayName: DRIVER LAYER, id: DRIVER LAYER}
children:
- type: ElementPosition
  attributes: {x: '51', y: '191', id: DRIVER LAYER}
- type: Attachments
  children:
  - type: Attachment
    attributes: {targetComponentID: BASIC CONFIGURATION, namespace: drvPic32mEthmac,
      id: libdrvPic32mEthmac, targetAttachmentID: 'tcpipNetConfig_0:NETCONFIG_MAC_Dependency'}
