format_version: v1.0
type: GroupComponent
attributes: {displayName: TCP/IP STACK, id: TCP/IP STACK}
children:
- type: ElementPosition
  attributes: {x: '469', y: '379', id: TCP/IP STACK}
- type: Attachments
  children:
  - type: Attachment
    attributes: {targetComponentID: drv_spi_0, namespace: DRIVER LAYER, id: 'drvExtMacEncx24j600_0:ENCX24J600_SPI',
      targetAttachmentID: drv_spi}
  - type: Attachment
    attributes: {targetComponentID: sys_console_0, namespace: BASIC CONFIGURATION,
      id: 'tcpipStack:Core_SysConsole_Dependency', targetAttachmentID: sys_console}
