format_version: v1.0
type: GroupComponent
attributes: {displayName: TCP/IP STACK, id: TCP/IP STACK}
children:
- type: ElementPosition
  attributes: {x: '517', y: '380', id: TCP/IP STACK}
- type: Attachments
  children:
  - type: Attachment
    attributes: {targetComponentID: sys_console_0, namespace: BASIC CONFIGURATION,
      id: 'tcpipStack:Core_SysConsole_Dependency', targetAttachmentID: sys_console}
