format_version: v1.0
type: UniqueComponent
attributes: {id: drvPic32mEthmac}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_INTMAC_PHY_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPic32mEthmac, value: LAN8740}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: ETHMAC_PHY_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drvExtPhyLan8740}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: libdrvExtPhyLan8740}
- type: ElementPosition
  attributes: {x: '405', y: '15', id: drvPic32mEthmac}
