format_version: v1.0
type: UniqueComponent
attributes: {id: tcpip_driver_config}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_ENCX24J600}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_ETHMAC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_LAN8720}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_LAN8740}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_AUTOCONFIG_ENABLE_MIIM_Driver}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '20', y: '20', id: tcpip_driver_config}
